### ISSUE TITLE
Suggested actions navigation arrows appear unnecessarily 

### ISSUE THREAD

**Issue by prejeanb** [microsoft/BotFramework-WebChat#2497]
## Screenshots
![image](https://user-images.githubusercontent.com/31588178/67580579-8d16d080-f714-11e9-86fd-49ad612c1c74.png)

## Version
Latest ES5 version from CDN... https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js

## Describe the bug
On certain Android phones in Chrome, the Suggested Actions navigation arrows appear unnecessarily.  

The Suggested Actions navigation arrows should only appear when needed.

## To Reproduce

1. Find a phone which specs similar to the following...
   Alcatel 5026D
   display:Size    6.0 inches
   Resolution    720 x 1440 pixels
   Android version 7.0
2. Navigate to a Web Chat using the latest webchat-es5 from the CDN and Suggested Actions
3. Perform some function that causes Suggested Actions to appear
4. See the that the Suggested Actions navigation arrows appear

## Expected behavior
Suggested Actions navigation arrows only appear when they are actually needed for scrolling

## Additional context

[Bug]

**Comment by corinagum** [comment]
@prejeanb thank you for filing this issue. 

I will have to hunt down an Android to test this out, but until then, could you clarify the behavior for me? 
From your screencap it looks like you are pointing out that the < > buttons are showing even though the length of suggested-actions does not need to scroll from side to side. Is that correct?

**Comment by prejeanb** [comment]
@corinagum Yes, that is exactly the behavior I'm reporting

**Comment by corinagum** [comment]
@prejeanb great, thanks for the clarification :)

**Comment by corinagum** [comment]
If this repros on a carousel, we should consider filing an issue with react-film and using this issue for tracking. @compulim @tdurnford, thoughts? I'll try and test a repro in the next week.

**Comment by corinagum** [comment]
@prejeanb, I believe this issue has been resolved with out `react-film` bump! Do you think you could help us verify? Please clone the Web Chat repo, and run the following commands: 

- `npm i`
- `npm run bootstrap`
- `npm run start`

Then navigate to `BotFramework-WebChat/packages/bundle/dist/` and copy paste one of the `.js` files in place of the CDN link on your project. 

I tested this on an Android using Chrome with the `webchat.js` file and the scroll buttons were no longer showing. I'm going to close this issue as resolved, but if the problem persists for you please let us know and I will reopen. Thanks!

**Comment by corinagum** [comment]
😂 Apparently I jumped the gun and the react-film PR isn't even merged in yet. Reopening this until #2632 is verified as a fix.

**Comment by corinagum** [comment]
Checking this code on latest, I am seeing on Android that the arrows no longer appear when unnecessary for suggested actions. Feel free to try out our latest `webchat.js` to test, and if you are having any further problems, please comment here. Thank you!

**Comment by prejeanb** [comment]
![image](https://user-images.githubusercontent.com/31588178/75243243-85853800-5797-11ea-95ce-e82152b7e1cb.png)

It looks like this is still occurring based on the screen above from an android device
