### ISSUE TITLE
Update Web Chat Samples to v4.6.0

### ISSUE THREAD

**Issue by narik1989** [microsoft/BotFramework-WebChat#2604]
Hi,

When sending an attachment from User to Bot. The user is unable to download the attachment. It opens a default placeholder url.

Steps to reproduce
1. https://microsoft.github.io/BotFramework-WebChat/12.customization-minimizable-web-chat/
2. Send any attachment (*.docx or *.doc)
3. See the response from the bot for uploaded url.

Please find below the screenshot attached for reference.

![Download](https://user-images.githubusercontent.com/33231617/68924490-fb483380-07a6-11ea-90da-8cf72aee110f.png)

Thanks
Kiran

**Comment by stevkan** [comment]
@narik1989, I just tested this using Chrome, Version 78.0.3904.97, with no issue. Tried with a .json and a .docx file with success on both attempts. Can you clear your browser cache and try again?

**Comment by tdurnford** [comment]
@narik1989 The [Minimizable Web Chat](https://microsoft.github.io/BotFramework-WebChat/12.customization-minimizable-web-chat/) Sample uses Web Chat v4.5.1, and there were a number of changes to how attachments are handled since that release. One of the changes removes the ability for users to download attachments they have uploaded. This should be resolved in v4.6.0.

**Comment by tdurnford** [comment]
Using this issue to track bumping the samples to the latest version of Web Chat.

**Comment by narik1989** [comment]
Thanks for the update @tdurnford. But i am still not able to download the document from the chat window.

Scenario
1) User sends an attachment to Bot
2) Bot responds with uploaded document

Issue: 
The message sent by bot works as it has the proper URL to download the file. But the url of the document/ image sent by the user turns to default placeholder image. 

My Chat Service
User 1 will be able to chat to User 2. When User 1 sends a document to User 2. User 2 is able to download and view it. But User 1 is unable to view/download what he has sent. This is a client requirement hence i am looking for a solution.


File Formats (.doc, .docx, .png, .jpg). Please find attached the screenshot for the same.

@stevkan - I am using the latest version as well.

![Doc](https://user-images.githubusercontent.com/33231617/69208604-31f0c600-0b7a-11ea-839b-b0f5bd9ba905.png)
![JPG](https://user-images.githubusercontent.com/33231617/69208605-32895c80-0b7a-11ea-9652-497a391997d6.png)
![Version](https://user-images.githubusercontent.com/33231617/69208606-32895c80-0b7a-11ea-9ad2-8280d533c586.png)

Thanks
Kiran

**Comment by tdurnford** [comment]
@Kiran can you check which version of Web Chat you are using? Users should only be able to download attachments sent from the bot - not attachments they have sent to the bot.

**Comment by narik1989** [comment]
Hi @tdurnford, i am just using the sample provided by Microsoft, please find the link below, in this if you upload any  (.doc, .docx, .png, .jpg) the document sent is not able to be downloaded.

https://microsoft.github.io/BotFramework-WebChat/12.customization-minimizable-web-chat/

Thanks
Kiran

**Comment by tdurnford** [comment]
Correct, the user should only be able to download attachments sent by the bot to the user. It's redundant to allow a user to download an attachment they sent to the bot since it is already on their machine.
