### ISSUE TITLE
Not Receiving Image From Chat

### ISSUE THREAD

**Issue by jsullboy** [Microsoft/BotFramework-WebChat#329]
The following runs fine using Skype and the bot framework emulator.

//in my c# bot code I am prompting for the user to upload an image
PromptDialog.Attachment(context, UploadReceivedAsync, message)

//in the UploadReceivedAsync method i receive the following values
var picture = attachments?.FirstOrDefault<Attachment>();
picture.ContentUrl //this has a url to a location
picture.ContentType //this is: "application/vnd.microsoft.activity" I was expecting "image"
//if I download the contents from the url in picture.contenturl I get the following:
{"type":"message","from":{"id":"I50Z4QpVy8f","name":"You"},"locale":"en-US","timestamp":"2017-02-04T14:25:35.781Z","channelData":{"clientActivityId":"1486218230997.8879779759784986.4"}}

Do I need to do something differently for the WebChat client? Or is this a bug in the current web chat?
I have an older BOT that uses the older version of webchat and this same code works fine.

Any suggestions would be appreciated

**Comment by billba** [comment]
Can you be a little more concrete about what behavior you are expecting from WebChat? I don't speak C# so I don't know what you are getting at here.

Are you using the latest emulator? It embeds WebChat so you should see the same behavior.

(Also "bot" is not an acronym, so we don't say BOT.)

**Comment by jsullboy** [comment]
Hi Bill

Thanks for the quick response.

The scenario is my Bot [:)] is prompting the user to upload a picture.

Using Edge with Web Chat the user is stuck in an endless loop as the open file window keeps opening. But it does send the image. But the user is stuck as they can't stop the open file window from opening.

Using FireFox it sends the image without the file window issue.

Using IE the send fails. 

Chrome I have not tested.

When I receive the message which should include the image as an attachment the content type of the attachment (should be the image that the user uploaded) is "application/vnd.microsoft.activity" and the URL to get the image contents points to a blob that has the json text I have in the original post.

What happens with Skype or the Bot emulator is: the response message has an attachment of type "image" and the content URL points to data for the image. I can download the image data from the URL and do my analysis of the image. But with the Web chat I can't do this because the attachment does not tell me where the image data is.

The Bot I wrote last month had similar functionality. When I open Web chat for that Bot it is still the older version of web chat and it works fine. How does 'https://webchat.botframework.com/embed/<bot id>?s=' decide which version of the web chat to show? Is there a way I can tell it to use the older version for now?

Seems like this is a bug in web chat is there a work around I can use?

Thanks

**Comment by jsullboy** [comment]
Hi Bill

As I was writing the previous post it occurred to me that there might be more than one attachment even though I am only expecting one and only uploading one image.

I tested it and there is indeed more than one attachment there are 2. The second attachment is the image.

So I updated my bot to loop through the attachments and find the image.

Not sure if the first attachment is intended. The older version of web chat did not have that.

**Comment by billba** [comment]
The Edge problem is unrelated, and was fixed in https://github.com/Microsoft/BotFramework-WebChat/pull/326

**Comment by danmarshall** [comment]
Hi @jsullboy, are you referring to the 2 attachments you are receiving from your bot:
```
[
    {
        "contentType": "application/vnd.microsoft.activity",
        "contentUrl": "https://webchat.botframework.com/attachments/AFl7z1dcbEo/0000004/0/blob?t=QbMbvfZtjq4.dAA.QQBGAGwANwB6ADEAZABjAGIARQBvAC0AMAAwADAAMAAwADAANAA.UGUmMrmA0gE.FzDKpfdY84k.bSUjZ6DhvdI0yOjarwxn-ZBIjBvbUG2cBmDQA8RNXro",
        "name": "blob"
    },
    {
        "contentType": "image/png",
        "contentUrl": "https://webchat.botframework.com/attachments/AFl7z1dcbEo/0000004/1/fuselabs.png?t=QbMbvfZtjq4.dAA.QQBGAGwANwB6ADEAZABjAGIARQBvAC0AMAAwADAAMAAwADAANAA.UGUmMrmA0gE.FzDKpfdY84k.bSUjZ6DhvdI0yOjarwxn-ZBIjBvbUG2cBmDQA8RNXro",
        "name": "fuselabs.png"
    }
]
```
One is the activity, and the other being the image itself?

**Comment by jsullboy** [comment]
Hi Dan,

Yes. I was not expecting the activity attachment. The older version did not attach the activity just the image.

Bill mentioned there is a fix for the Edge browser where the file open window is continuously opened. 

When will the fix be released? I still have the issue with edge.

I am assuming that the fixes are deployed to webchat.botframework.com?

**Comment by billba** [comment]
This is a bug. You should not be getting the activity attachment. This worked not long ago, so something regressed somewhere. I'm looking into it.

@jsullboy the WebChat channel lags behind the current build by about a week

**Comment by billba** [comment]
Confirmed as a bug in Direct Line. A fix is en route.

**Comment by billba** [comment]
I have confirmed that the change to Direct Line has been deployed and fixes this issue.
